### ISSUE TITLE
Nice implementation

### ISSUE THREAD

**Issue by ccsmm78** [chongduan/MRI-AUTOMAP#3]
Very nice implementation for AUTOMAP which was presented in Nature paper.

I want to run your code, but I don't know how to prepare the images or run script.
If you don't mind, I'd like to know those.

Thanks a lot~

**Comment by chongduan** [comment]
Hi, sorry for my late response. Unfortunately, I am not allowed to share the cardiac MRI data I used. Having said that, you should be able to use any imaging data for testing the reconstruction method. The ImageNet should work as well.
