### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by mortezasj11** [chongduan/MRI-AUTOMAP#4]
Hi Chongduan

Did you also provide the dataset?
How can I have access to it?

Best,
morteza

**Comment by HarishKongari** [comment]
Dear Chongduan,

Could you also provide the dataset?
So that I can check out how automap works.

Best Regards,
Harish Kongari

**Comment by chongduan** [comment]
Hi Morteza and Harish, 

Unfortunately, I am not allowed to share the cardiac MRI data due to privacy issue. However, I think you can use any public MRI data to test the model. The k-space data can be easily obtained via an inverse FFT. (this is not ideal though).
